version: '3.8'

services:
  api:
    build: .
    container_name: aegis-nids-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./app/data:/app/app/data
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - MODEL_PATH=app/models/model.pkl
      - IDLE_THRESHOLD=5000000
      - PREDICTION_THRESHOLD=0.035
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
